name: Run Python with requests and re

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install requests
      run: pip install requests

    - name: Run script
      run: python main.py
